services:
  chroma:
    image: chromadb/chroma
    container_name: chroma
    networks:
      - AI-bridge
    # env_file:
    # - .env
    environment:
      ANONYMIZED_TELEMETRY: "False"
networks:
  AI-bridge:
    external: true
    name: AI-bridge